collectibles_database/collectibles_database/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('', include('collectibles_db_app.urls')),
    path('profile/', include('user_profile.urls')),
    path('accounts/', include('django.contrib.auth.urls')),
    path('admin/', admin.site.urls),
] + (static(settings.STATIC_URL, document_root=settings.STATIC_ROOT) \
  + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT))

collectibles_database/collectibles_db_app/urls.py
from django.urls import path

from . import views

urlpatterns = [
    path('', views.index, name='index'),
    path('collectibles_list/', views.CollectiblesListView.as_view(), name='collectibles_list'),
    path('collectibles/item_detail/<int:pk>/', views.item_detail, name='item_detail'),
    path('friend_collectibles_list/<int:user_id>/', views.FriendCollectiblesListView.as_view(), name='friend_collectibles_list'),
    path('collectibles/update/<int:pk>/', views.UpdateItemView.as_view(), name='update_item'),
    path('collectibles/create/', views.CreateItemView.as_view(), name='create_new_item'),
    path('collectibles/delete/<int:pk>/', views.DeleteItemView.as_view(), name='delete_item'),
    path('get_values/', views.get_values, name='get_values'),
    path('collectibles/statistics', views.statistics_view, name='statistics'),
    path('collectibles/about', views.about_view, name='about'),
]

collectibles_database/user_profile/urls.py
from django.urls import path

from . import views

urlpatterns = [
    path('signup/', views.signup, name='signup'),
    path('profile/', views.profile, name='profile'),
    path('profile/<int:user_id>/', views.profile, name='profile'),
    path('profile/update/', views.profile_update, name='profile_update'),
    path('profile/search/', views.ProfileSearchView.as_view(), name='profile_search'),
    path('profile/send_friend_request/<int:user_id>/', views.send_friend_request, name='send_friend_request'),
    path('friends/list/', views.friends_list, name='friends_list'),
    path('notifications/', views.notifications, name='notifications'),
    path('preferences/', views.preferences, name='preferences'),
    path('profile/unfollow_friend/<int:user_id>/', views.unfollow_friend, name='unfollow_friend'),
    path('profile/delete/', views.ProfileDeleteView.as_view(), name='profile_delete'),
    path('delete_confirmation/', views.profile_delete_confirmation, name='profile_delete_confirmation'), # for now it messages that profile succesfully deleted, later it will messages user to confirm delete on email
]

collectibles_database/collectibles_db_app/models.py
from django.contrib.auth import get_user_model
from django.db import models
from django.urls import reverse
from django.utils.translation import gettext_lazy as _
from PIL import ExifTags, Image

User = get_user_model()


class GradationSystem(models.Model):
    name = models.CharField(_("name"), max_length=100)
    description = models.TextField(_("description"), null=True, blank=True)

    class Meta:
        verbose_name = _("gradation_system")
        verbose_name_plural = _("gradation_systems")

    def __str__(self):
        return f"{self.name}"


class Value(models.Model):
    value = models.CharField(_("value"), max_length=50, null=True, blank=True)
    description = models.TextField(_("description"), null=True, blank=True)
    picture = models.ImageField(
        _("picture"),
        upload_to='collectibles/gradation_value',
        null=True,
        blank=True,
        )
    gradation_system = models.ForeignKey(
        GradationSystem,
        verbose_name=_("gradation_system"),
        on_delete=models.CASCADE,
        related_name="values",
        )

    class Meta:
        verbose_name = _("value")
        verbose_name_plural = _("values")

    def __str__(self):
        return f"{self.value}"

    def get_absolute_url(self):
        return reverse("value_detail", kwargs={"pk": self.pk})


class ItemType(models.Model):
    name = models.CharField(_("name"), max_length=50)
    description = models.TextField(_("description"), null=True, blank=True)
    picture = models.ImageField(
        _("picture"),
        upload_to='collectibles/item_type',
        null=True,
        blank=True,
        )

    class Meta:
        verbose_name = _("item_type")
        verbose_name_plural = _("item_types")

    def __str__(self):
        return f"{self.name}"

    def get_absolute_url(self):
        return reverse("itemtype_detail", kwargs={"pk": self.pk})


class CollectibleItem(models.Model):
    user = models.ForeignKey(
        User,
        verbose_name=_("user"),
        on_delete=models.CASCADE,
        related_name="collectible_items"
        )
    country = models.CharField(_("country"), max_length=100)
    currency = models.CharField(_("currency"), max_length=100, null=True, blank=True)
    release_year = models.PositiveIntegerField(_("release_year"))
    circulation = models.PositiveIntegerField(_("circulation"), null=True, blank=True)
    item_type = models.ForeignKey(
        ItemType,
        verbose_name=_("item_type"),
        on_delete=models.SET_NULL,
        null=True,
        blank=True,
        related_name="collectible_items"
    )
    denomination = models.FloatField(_("denomination"), null=True, blank=True)
    quantity = models.PositiveIntegerField(_("quantity"))
    condition = models.ForeignKey(
        GradationSystem,
        verbose_name=_("condition"),
        on_delete=models.SET_NULL,
        null=True,
        blank=True,
        related_name="collectible_items"
    )
    value = models.ForeignKey(
        Value,
        verbose_name=_("value"),
        on_delete=models.SET_NULL,
        null=True,
        blank=True,
        related_name="collectible_items"
    )
    
    description = models.TextField(_("description"), max_length=3000, null=True, blank=True)
    obverse_side = models.ImageField(
        _("obverse_side"),
        upload_to='collectibles/obverse_side',
        null=True,
        blank=True,
        )
    reverse_side = models.ImageField(
        _("reverse_side"),
        upload_to='collectibles/reverse_side',
        null=True,
        blank=True,
        )
    register_date = models.DateTimeField(_("register_date"), auto_now_add=True)
    update_date = models.DateTimeField(_("update date"), null=True, blank=True)
    

    class Meta:
        verbose_name = _("collectible_item")
        verbose_name_plural = _("collectible_items")

    def __str__(self):
        return self.country

    def get_absolute_url(self):
        return reverse("collectibleitem_detail", kwargs={"pk": self.pk})
    
    # item verification
    # def find_similar_items(self, user):
    #     return CollectibleItem.objects.filter(
    #         user=user,
    #         country=self.country,
    #         release_year=self.release_year,
    #         item_type=self.item_type,
    #         denomination=self.denomination,
    #     ).exclude(pk=self.pk)


    # This part is for keeping images in their original orientation and resizing
    def _rotate_image(self, image):
        try:
            # Check if the image has an EXIF orientation tag
            for orientation in ExifTags.TAGS.keys():
                if ExifTags.TAGS[orientation] == 'Orientation':
                    break
            exif = dict(image._getexif().items())

            if orientation in exif:
                if exif[orientation] == 3:
                    image = image.rotate(180, expand=True)
                elif exif[orientation] == 6:
                    image = image.rotate(270, expand=True)
                elif exif[orientation] == 8:
                    image = image.rotate(90, expand=True)
        except (AttributeError, KeyError, IndexError):
            # Ignore if the image doesn't have EXIF data or orientation tag
            pass

        return image

    def _resize_and_save_image(self, field_name):
        image_field = getattr(self, field_name)
        if image_field:
            image = Image.open(image_field.path)
            image = self._rotate_image(image)
            if image.width > 600 or image.height > 600:
                new_size = (600, 600)
                image.thumbnail(new_size)
            image.save(image_field.path)

    def save(self, *args, **kwargs):
        super().save(*args, **kwargs)
        self._resize_and_save_image('obverse_side')
        self._resize_and_save_image('reverse_side')

collectibles_database/collectibles_db_app/forms.py
from django import forms

from . import models


class CreateItemForm(forms.ModelForm):
    condition = forms.ModelChoiceField(
        queryset=models.GradationSystem.objects.all(),
        widget=forms.Select(attrs={'class': 'form-control', 'id': 'id_condition'})
    )
    value = forms.ModelChoiceField(
        queryset=models.Value.objects.none(),
        widget=forms.Select(attrs={'class': 'form-control', 'id': 'id_value'})
    )

    item_type = forms.ModelChoiceField(
        queryset=models.ItemType.objects.all(),
        widget=forms.Select(attrs={'class': 'form-control', 'id': 'id_item_type'})
    )

    class Meta:
        model = models.CollectibleItem
        fields = (
            'user', 'country', 'currency', 'release_year', 'circulation',
            'item_type', 'denomination', 'quantity', 'condition', 'value',
            'description', 'obverse_side', 'reverse_side', 'update_date'
        )
        widgets = {
            'user': forms.HiddenInput(),
            'update_date': forms.HiddenInput(),
        }

    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        self.fields['value'].queryset = models.Value.objects.none()

        if 'condition' in self.data:
            try:
                condition_id = int(self.data.get('condition'))
                self.fields['value'].queryset = models.Value.objects.filter(
                    gradation_system_id=condition_id)
            except (ValueError, TypeError):
                pass
        elif self.instance.pk:
            self.fields['value'].queryset = self.instance.condition.value.all()
            

class UpdateItemForm(forms.ModelForm):
    condition = forms.ModelChoiceField(
        queryset=models.GradationSystem.objects.all(),
        widget=forms.Select(attrs={'class': 'form-control', 'id': 'id_condition'})
    )
    value = forms.ModelChoiceField(
        queryset=models.Value.objects.none(),
        widget=forms.Select(attrs={'class': 'form-control', 'id': 'id_value'})
    )

    item_type = forms.ModelChoiceField(
        queryset=models.ItemType.objects.all(),
        widget=forms.Select(attrs={'class': 'form-control', 'id': 'id_item_type'})
    )

    class Meta:
        model = models.CollectibleItem
        fields = (
            'user', 'country', 'currency', 'release_year', 'circulation',
            'item_type', 'denomination', 'quantity', 'condition', 'value',
            'description', 'obverse_side', 'reverse_side', 'update_date'
        )
        widgets = {
            'user': forms.HiddenInput(),
            'update_date': forms.HiddenInput(),
        }

    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        self.fields['value'].queryset = models.Value.objects.none()

        if 'condition' in self.data:
            try:
                condition_id = int(self.data.get('condition'))
                self.fields['value'].queryset = models.Value.objects.filter(
                    gradation_system_id=condition_id
                )
            except (ValueError, TypeError):
                pass
        elif self.instance.pk:
            self.fields['value'].queryset = self.instance.condition.values.all()
            

class FilterForm(forms.Form):
    country = forms.CharField(max_length=100, required=False)
    item_type = forms.ModelChoiceField(queryset=models.ItemType.objects.all(), required=False, empty_label='Select Item Type')
    release_year = forms.CharField(max_length=100, required=False)
    currency = forms.CharField(max_length=100, required=False)

collectibles_database/collectibles_db_app/templates/collectibles_database/collectible_item_delete.html
{% extends 'base.html' %}

{% block title %} Delete Item {% endblock title %}

{% block content %}
<div class="dialog-message">
    <h2>Do you really want to delete this record?</h2>
</div>
<div class="item-detail-container">
    <div class="item-detail-img">
        {% if object.obverse_side %}
            <img class="item-front-image" src="{{ object.obverse_side.url }}">
        {% endif %}
        {% if object.reverse_side %}
            <img class="item-front-image" src="{{ object.reverse_side.url }}">
        {% endif %}
    </div>
    <div class="item-detail-contents">
        <ul>
            <li>Country: {{ object.country }}</li>
            <li>Item Type: {{ object.get_item_type_display }}</li>
            <li>Release Year: {{ object.release_year }}</li>
            <li>Quantity: {{ object.quantity }}</li>
            <br>
            {% if object.currency %}
                <li>Currency: {{ object.currency }}</li>
            {% endif %}
            {% if object.circulation %}
                <li>Circulation: {{ object.circulation }}</li>
            {% endif %}
            {% if object.denomination %}
                {% comment %} removing .0 if it is .0 from variable {% endcomment %}
                {% if object.denomination|floatformat:0|stringformat:"s" == object.denomination|floatformat:0 %}
                <li>Denomination: {{ object.denomination|floatformat }}</li>
                {% else %}
                <li>Denomination: {{ object.denomination }}</li>
                {% endif %}
            {% endif %}
            <li>Item condition:
                <ul>
                    <li>Grading System: {{ object.condition }}</li>
                    <li>Value: {{ object.value }}</li>
                </ul>
            </li>
            <li>Description: {{ object.description }}</li>
            <li>Register Date: {{ object.register_date }}</li>
            {% if object.update_date %}
            <li>Last Changes: {{ object.update_date }}</li>
            {% endif %}
        </ul>
    </div>
    <div class="ask-delete-dialog">
        <form action="{{ request.path }}" method="post">
            {% csrf_token %}
            <button type="submit">Confirm</button>
            <a href="{{ request.META.HTTP_REFERER }}">Cancel</a>
        </form>
    </div>
</div>

{% endblock content %}

collectibles_database/collectibles_db_app/templates/collectibles_database/collectible_item_detail.html
{% extends 'base.html' %}

{% block title %} Item Detail {% endblock title %}

{% block content %}
<div class="dialog-message">
    <h2>Item Details</h2>
</div>
<div class="item-detail-container">
    <div class="item-detail-img">
        {% if item.obverse_side %}
            <img class="item-front-image" src="{{ item.obverse_side.url }}">
        {% endif %}
        {% if item.reverse_side %}
            <img class="item-front-image" src="{{ item.reverse_side.url }}">
        {% endif %}
    </div>
    <div class="item-detail-contents">
        <ul>
            <li>Country: {{ item.country }}</li>
            <li>Item Type: {{ item.get_item_type_display }}</li>
            <li>Release Year: {{ item.release_year }}</li>
            <li>Quantity: {{ item.quantity }}</li>
            <br>
            {% if item.currency %}
                <li>Currency: {{ item.currency }}</li>
            {% endif %}
            {% if item.circulation %}
                <li>Circulation: {{ item.circulation }}</li>
            {% endif %}
            {% if item.denomination %}
                {% comment %} removing .0 if it is .0 from variable {% endcomment %}
                {% if item.denomination|floatformat:0|stringformat:"s" == item.denomination|floatformat:0 %}
                <li>Denomination: {{ item.denomination|floatformat:"-2" }}</li>
                {% else %}
                <li>Denomination: {{ item.denomination }}</li>
                {% endif %}
            {% endif %}
            <li>Item condition:
                <ul>
                    <li>Grading System: {{ item.condition }}</li>
                    <li>Value: {{ item.value }}</li>
                </ul>
            </li>
            <li>Description: {{ item.description }}</li>
            <li>Register Date: {{ item.register_date }}</li>
            {% if item.update_date %}
            <li>Last Changes: {{ item.update_date }}</li>
            {% endif %}
        </ul>
    </div>
    <div class="ask-action-dialog">
        {% comment %} If the listing does not belong to friend {% endcomment %}
        {% if user.is_authenticated and item.user == user %}
            <a href="{% url 'update_item' item.pk %}">Update</a>
            <a href="{% url 'delete_item' item.pk %}">Delete</a>
        {% endif %}
        <a href="{{ request.META.HTTP_REFERER }}">Go Back</a>
    </div>
    
</div>

{% endblock content %}

collectibles_database/collectibles_db_app/templates/collectibles_database/collectible_item_form.html
{% extends 'base.html' %}

{% block title %} {{ block.super }} {% endblock title %}

{% block content %}
<div class="item-form-container">
    {% if object.id %}
    <h2>Update item record</h2>
    {% else %}
    <h2>Add item to the list</h2>
    {% endif %}
    <form method="post" action="{{ request.path }}?collectibleitem_id={{ collectibleitem.id }}" enctype="multipart/form-data">
        {% csrf_token %}
        {% for hidden_field in form.hidden_fields %}
            {{ hidden_field }}
        {% endfor %}
            <div class="form-group">
                <label for="id_country">Country<span class="red-asterisk">*</span></label>
                {{ form.country }}
            </div>
            <div class="form-group">
                <label for="id_item_type">Item Type<span class="red-asterisk">*</span></label>
                {{ form.item_type }}
                <p>See more about item types in "About" page</p>
            </div>
            <div class="form-group">
                <label for="id_release_year">Release Year<span class="red-asterisk">*</span></label>
                {{ form.release_year }}
            </div>
            <div class="form-group">
                <label for="id_quantity">Quantity<span class="red-asterisk">*</span></label>
                {{ form.quantity }}
            </div>
            <div class="form-group">
                <label for="id_currency">Currency</label>
                {{ form.currency }}
            </div>
            <div class="form-group">
                <label for="id_denomination">Denomination</label>
                {{ form.denomination }}
            </div>
            <div class="form-group">
                <label for="id_circulation">Circulation</label>
                {{ form.circulation }}
            </div>
            <hr>
            <div class="form-group">
                <label><strong>Item Condition</strong></label>
                <p>Check 'Other' if you are not sure, see more in "About" page</p>
                <div class="nested-form-group">
                    <label for="id_condition">Grading System<span class="red-asterisk">*</span></label>
                    {{ form.condition }}
                </div>
                <div class="nested-form-group">
                    <label for="id_value">Value<span class="red-asterisk">*</span></label>
                    {{ form.value }}
                </div>
            </div>
            <hr>
            <div class="form-group">
                <label for="id_description">Description</label>
                {{ form.description }}
            </div>
            <hr>
            <div class="form-group">
                <label><strong>Item Images</strong></label>
                <div class="nested-form-group">
                    <label for="id_obverse_side">Obverse Side</label>
                    {{ form.obverse_side }}
                    <p>Horizontal 4:3 images recommended</p>
                </div>
                <div class="nested-form-group">
                    <label for="id_reverse_side">Reverse Side</label>
                    {{ form.reverse_side }}
                    <p>Horizontal 4:3 images recommended</p>
                </div>
            </div>
            <hr>
        <p><span class="red-asterisk">*</span> - required fields</p>
        <button type="submit">Confirm</button>
    </form>
</div>
<script>
    console.log("hello")
    $(document).ready(function () {
    // Disable the dependent dropdown initially
    // $('#id_value').prop('disabled', true);
  
    // Handle the change event of the 'condition' dropdown
    $('#id_condition').on('change', function () {
        var gradationSystemId = $(this).val();
        var valueSelect = $('#id_value');
  
        // Clear and disable the dependent dropdown
        valueSelect.empty().prop('disabled', true);
  
        // Fetch the related Value objects based on the selected GradationSystem
        $.ajax({
            url: '{% url "get_values" %}',
            type: 'GET',
            data: {
                gradation_system_id: gradationSystemId
            },
            success: function (data) {
            // Enable the Value dropdown and populate it with the fetched data
                valueSelect.prop('disabled', false);
  
                $.each(data.values, function (key, value) {
                    valueSelect.append($('<option>').text(value.value).attr('value', value.id));
                });
            }
        });
    });
    });
</script>
<script>
    const socket = new WebSocket('ws://' + window.location.host + '/ws/some_path/');

    socket.onopen = function (event) {
        console.log('WebSocket opened:', event);
    };

    socket.onmessage = function (event) {
        const data = JSON.parse(event.data);

        // Handle the verification result
        if (data.verification_result === 'matched') {
            displayMatchingItems(data.matching_items);
        }
    };

    socket.onclose = function (event) {
        console.log('WebSocket closed:', event);
    };

    function sendVerificationRequest(itemData) {
        socket.send(JSON.stringify(itemData));
    }

    function displayMatchingItems(matchingItems) {
        // Implement logic to display matching items on the page
        // You can use jQuery or plain JavaScript for DOM manipulation
        // For example:
        const matchingItemsContainer = document.getElementById('matching-items');
        matchingItemsContainer.innerHTML = '<p>Your item matches the following existing items:</p>';
        const itemList = document.createElement('ul');
        matchingItems.forEach(item => {
            const listItem = document.createElement('li');
            listItem.textContent = `${item.country} - ${item.release_year}`;
            itemList.appendChild(listItem);
        });
        matchingItemsContainer.appendChild(itemList);
    }
</script>

{% endblock content %}

collectibles_database/collectibles_db_app/templates/collectibles_database/collectibles_statistics.html
{% extends 'base.html' %}

{% block title %} Statistics {% endblock title %}

{% block content %}

{% if total_records > 0 %}
<div class="statistics-container">
    <h2>User: {{ user.username }}</h2>
    <ul class="statistics-list">
        <li><strong>Total listings:</strong> {{ total_records }}</li>
        <li><strong>Total items:</strong> {{ total_items }}</li>
        <li><strong>Oldest item date:</strong> {{ oldest_item }}</li>
        <li><strong>Newest item date:</strong> {{ newest_item }}</li>
        <li><strong>Average year of items:</strong> {{ average_year }}</li>
    </ul>
    <table class="item-type-table">
        <caption><strong>Statistics by item type</strong></caption>
        <tr>
            <th>Item Type</th>
            <th>Total Records</th>
            <th>Total Items</th>
            <th>Oldest Item (date)</th>
            <th>Newest Item (date)</th>
        </tr>
        {% for stat in item_type_stats %}
        <tr>
            <td>{{ stat.item_type }}</td>
            <td>{{ stat.total_records }}</td>
            <td>{{ stat.total_items }}</td>
            <td>{{ stat.oldest_item }}</td>
            <td>{{ stat.newest_item }}</td>
        </tr>
        {% endfor %}
    </table>
</div>
{% else %}
<h2>There are no items in your collectibles list to form statistics</h2>
{% endif %}

{% endblock content %}

collectibles_database/collectibles_db_app/templates/collectibles_database/friend_collectibles_list.html
{% extends 'base.html' %}
{% load static %}
{% load custom_filters %}

{% block title %} {{ block.super }} {% endblock title %} 

{% block search_bar %}
{% include 'includes/search.html' %}
{% endblock search_bar %}

{% block content %}


{% if friend_collectibles_list %}
<h2 id="friend-name">{{ friend.username }}'s collectibles list</h2>
{% include 'includes/paginator_nav.html' %}

{% if display_style == 1 %}
    <div class="sort-options">
        <a href="?sort_by=country{% if request.GET.query %}&query={{ request.GET.query }}{% endif %}&order={{ request.GET.order|toggle_order }}">Sort by Country</a>
        <a href="?sort_by=release_year{% if request.GET.query %}&query={{ request.GET.query }}{% endif %}&order={{ request.GET.order|toggle_order }}">Sort by Release Year</a>
    </div>
{% endif %}

{% if display_style == 1 %}
    <div class="items-grid-container">
        {% for item in friend_collectibles_list %}
        <div>
            <div class="content-container">
            <div>
            <a href="{% url 'item_detail' item.pk %}">
                {% if item.obverse_side %}
                    <img class="item-front-image" src="{{ item.obverse_side.url }}">
                {% else %}
                    <img class="item-front-image" src="{% static 'collectibles/img/noimage.png' %}">
                {% endif %}
            </a>
            </div>
            <div>Country: {{ item.country }}</div>
            <div>Item type: {{ item.get_item_type_display }}</div>
            <div>Release Year: {{ item.release_year }}</div>
            <div>Quantity: {{ item.quantity }}</div>
            {% if item.currency %}
                <div>Currency: {{ item.currency }}</div>
            {% endif %}
            {% if item.denomination %}
                {% comment %} removing .0 if it is .0 from variable {% endcomment %}
                {% if item.denomination|floatformat:0|stringformat:"s" == item.denomination|floatformat:0 %}
                <div>Denomination: {{ item.denomination|floatformat:"-2" }}</div>
                {% else %}
                <div>Denomination: {{ item.denomination }}</div>
                {% endif %}
            {% endif %}
            </div>
            <div class="list-item-buttons">
                <a href="{% url 'item_detail' item.pk %}">View Details</a>
            </div>
        </div>
        {% endfor %}
    </div>
{% elif display_style == 2 %}
<div class="table-background">
    <table class="items-list-container">
        <thead>
            <tr>
                <th></th>
                <th><a href="?sort_by=country{% if request.GET.query %}&query={{ request.GET.query }}{% endif %}&order={{ request.GET.order|toggle_order }}">Country</a></th>
                <th>Item Type</th>
                <th><a href="?sort_by=release_year{% if request.GET.query %}&query={{ request.GET.query }}{% endif %}&order={{ request.GET.order|toggle_order }}">Release Year</a></th>
                <th><a href="?sort_by=quantity{% if request.GET.query %}&query={{ request.GET.query }}{% endif %}&order={{ request.GET.order|toggle_order }}">Quantity</a></th>
                <th><a href="?sort_by=currency{% if request.GET.query %}&query={{ request.GET.query }}{% endif %}&order={{ request.GET.order|toggle_order }}">Currency</a></th>
                <th><a href="?sort_by=denomination{% if request.GET.query %}&query={{ request.GET.query }}{% endif %}&order={{ request.GET.order|toggle_order }}">Denomination</a></th>
                <th><a href="?sort_by=register_date{% if request.GET.query %}&query={{ request.GET.query }}{% endif %}&order={{ request.GET.order|toggle_order }}">Register Date</a></th>
            </tr>
        </thead>
        <tbody>
            {% for item in friend_collectibles_list %}
                <tr>
                    <td>
                        <a href="{% url 'item_detail' item.pk %}">
                        {% if item.obverse_side %}
                            <img class="item-small-image" src="{{ item.obverse_side.url }}">
                        {% else %}
                            <img class="item-small-image" src="{% static 'collectibles/img/noimage.png' %}">
                        {% endif %}
                        </a>
                    </td>
                    <td><a href="{% url 'item_detail' item.pk %}">{{ item.country }}</a></td>
                    <td><a href="{% url 'item_detail' item.pk %}">{{ item.item_type }}</a></td>
                    <td><a href="{% url 'item_detail' item.pk %}">{{ item.release_year }}</a></td>
                    <td><a href="{% url 'item_detail' item.pk %}">{{ item.quantity }}</a></td>
                    <td><a href="{% url 'item_detail' item.pk %}">{{ item.currency|default:"-" }}</a></td>
                    <td><a href="{% url 'item_detail' item.pk %}">{{ item.denomination|default:"-" }}</a></td>
                    <td><a href="{% url 'item_detail' item.pk %}">{{ item.register_date }}</a></td>
                </tr>
            {% endfor %}
        </tbody>
    </table>
</div>
{% endif %}
{% include 'includes/paginator_pages.html' %}

{% else %}
<h2>No items found in {{ friend.username }}'s collectibles list</h2>
{% endif %}

{% endblock content %}

collectibles_database/collectibles_db_app/templates/collectibles_database/item_verification.html
{% extends 'base.html' %}

{% block title %}Similar Items{% endblock title %}

{% block content %}
  <h2>Similar Items</h2>

  {% if similar_items %}
    <ul>
      {% for item in similar_items %}
        <li>
          <strong>Country:</strong> {{ item.country }}<br>
          <strong>Release Year:</strong> {{ item.release_year }}<br>
          <strong>Item Type:</strong> {{ item.item_type.name }}<br>
          <!-- Add more fields as needed -->
        </li>
      {% endfor %}
    </ul>
  {% else %}
    <p>No similar items found.</p>
  {% endif %}
{% endblock content %}